### ISSUE TITLE
RAC Aufträge Annehmen

### ISSUE THREAD

**Issue by Chernarus** [A3ReallifeRPG/RealLifeRPGLauncher#3]
Wir können zurzeit immer nur 1 Auftrag beim RAC von denn Zivilisten Annehmen. Dies bitte Ändern. :-)

**Comment by vabene1111** [comment]
Dieser Bugtracker ist nur für den Launcher, bitte nutz für ingame den hier https://forum.realliferpg.de/wpbt/index.php?product/2-reallife-rpg/
