### ISSUE TITLE
issue on run dist

### ISSUE THREAD

**Issue by jackmsimo** [A3ReallifeRPG/RealLifeRPGLauncher#8]
[2018-02-05T15_21_37_581Z-debug.log](https://github.com/A3ReallifeRPG/RealLifeRPGLauncher/files/1695638/2018-02-05T15_21_37_581Z-debug.log)

**Comment by Kaibu** [comment]
You have to first set up everything yourself for your own build enviroment.

The issues you're having look like node-gyp is having issues, just look into how to properly build electron apps, there is a npm package that will install the required c++ runtimes, python and node for you.
